In [1]:
import pandas as pd

In [8]:
train = pd.read_csv('train_c.csv')
test = pd.read_csv('test_c.csv')

In [3]:
FScore

                                   Feature  Score
0                                  full_sq   1185
1                                  life_sq    473
2                                    floor    359
3                               build_year    291
4                                max_floor    275
5                                 kitch_sq    163
6                                 num_room    129
7                                    state    119
8                          kindergarten_km    102
9                              railroad_km    101
10                           green_zone_km     95
11                            radiation_km     85
12                                material     80
13                                sub_area     78
14             public_transport_station_km     77
15                                  ttk_km     76
16                          metro_min_avto     75
17                           industrial_km     73
18                               mosque_km     69
19                           metro_km_avto     66
20                              fitness_km     65
21                            swim_pool_km     64
22                            big_road2_km     63
23                           workplaces_km     63
24                           university_km     59
25                         preschool_quota     56
26                     hospital_beds_raion     56
27                                ID_metro     56
28                         green_part_1500     56
29                                 park_km     56
..                                     ...    ...
238                    cafe_avg_price_3000      3
239                     leisure_count_5000      3
240                        big_road1_1line      3
241  school_education_centers_top_20_raion      3
242             cafe_count_2000_price_high      3
243                              16_29_all      3
244  raion_build_count_with_builddate_info      3
245                  big_church_count_2000      3
246                            7_14_female      3
247                               0_6_male      3
248                               work_all      3
249                        ID_bus_terminal      3
250                      mosque_count_2000      2
251                     leisure_count_1000      2
252                       build_count_wood      2
253                            work_female      2
254                        radiation_raion      2
255                              work_male      2
256                       market_count_500      2
257                  nuclear_reactor_raion      2
258              thermal_power_plant_raion      2
259                           young_female      2
260                   big_church_count_500      2
261              cafe_count_500_price_high      1
262               detention_facility_raion      1
263                              young_all      1
264                           16_29_female      1
265                        build_count_mix      1
266              cafe_count_500_price_4000      1
267                   ID_railroad_terminal      1

[268 rows x 2 columns]

In [4]:
train = pd.read_csv('train_c.csv')

In [7]:
set(list(train['ID_railroad_terminal']))

{5, 32, 50, 83, 97, 101, 113, 121}