In [4]:
import warnings
warnings.filterwarnings('ignore')
%run Functions.py

In [12]:
sub = pd.read_csv('submission/Average_Sklearnstacking_Best.csv')

In [11]:
sub

        ID           y
0        1   80.107159
1        2   96.926023
2        3   79.418289
3        4   80.247614
4        5  120.152005
5        8   94.424351
6       10  113.662528
7       11   95.206356
8       12  117.265498
9       14   95.143291
10      15  117.061378
11      16  105.164223
12      17  101.045084
13      19   95.102239
14      20  105.108727
15      21  102.279040
16      22  117.330491
17      23  100.722046
18      26   96.458828
19      28   94.448679
20      29   96.023089
21      33   95.925192
22      35   95.009199
23      41   96.339993
24      42   94.548347
25      43  116.920598
26      45  104.030514
27      46  104.287102
28      51   94.216000
29      53   80.035078
...    ...         ...
4179  8361  109.749377
4180  8363  103.137082
4181  8364   92.587528
4182  8365   92.938971
4183  8366  101.807040
4184  8370  110.116822
4185  8372   91.883816
4186  8376   93.510653
4187  8377  110.301505
4188  8379  109.922673
4189  8380   93.101877
4190  8381  111.017342
4191  8386   91.677195
4192  8388  101.681855
4193  8389   92.185410
4194  8391  110.865306
4195  8394   93.479775
4196  8396  103.085023
4197  8398  101.915475
4198  8400  111.458772
4199  8401   92.254214
4200  8404   91.706580
4201  8407   95.528279
4202  8408  111.370736
4203  8409  109.497872
4204  8410  102.990081
4205  8411   94.661396
4206  8413   94.932137
4207  8414  110.418096
4208  8416   94.484365

[4209 rows x 2 columns]

In [13]:
leaks = {
    1:71.34112,
    12:109.30903,
    23:115.21953,
    28:92.00675,
    42:87.73572,
    43:129.79876,
    45:99.55671,
    57:116.02167,
    3977:132.08556,
    88:90.33211,
    89:130.55165,
    93:105.79792,
    94:103.04672,
    1001:111.65212,
    104:92.37968,
    72:110.54742,
    78:125.28849,
    105:108.5069,
    110:83.31692,
    1004:91.472,
    1008:106.71967,
    1009:108.21841,
    973:106.76189,
    8002:95.84858,
    8007:87.44019,
    1644:99.14157,
    337:101.23135,
    253:115.93724,
    8416:96.84773,
    259:93.33662,
    262:75.35182,
    1652:89.77625
    }
sub['y'] = sub.apply(lambda r: leaks[int(r['ID'])] if int(r['ID']) in leaks else r['y'], axis=1)
#sub.to_csv('stacked-models.csv', index=False)

In [15]:
sub.to_csv('submission/With_leakage_best_model.csv',index=False)